### ISSUE TITLE
SQL error -G Permission(s) Unset

### ISSUE THREAD

**Issue by Kreeman** [rmcgirr83/hidemyprofile#1]
When the permission for HMP isn't set (or just plain no/never) for a particular group, its users form (UCP Global Settings) generates/shows an SQL error on submit ...

Say -user_hmp cannot be NULL ...

**Comment by rmcgirr83** [comment]
user_hmp is set to 0 as default in the database

https://github.com/rmcgirr83/hidemyprofile/blob/v1.0.0/migrations/initial_schema.php#L30

Not sure what "users form (UCP Global Setting)" is.  Please explain this in more detail.

**Comment by Kreeman** [comment]
> user_hmp is set to 0 as default in the database
> 
> https://github.com/rmcgirr83/hidemyprofile/blob/v1.0.0/migrations/initial_schema.php#L30
> 
> Not sure what "users form (UCP Global Setting)" is. Please explain this in more detail.

A user gets an SQL error in the "UCP Global Setting" page if they don't have the permission to use the HMP feature ....

**Comment by Kreeman** [comment]
> user_hmp is set to 0 as default in the database
> 
> https://github.com/rmcgirr83/hidemyprofile/blob/v1.0.0/migrations/initial_schema.php#L30
> 
> Not sure what "users form (UCP Global Setting)" is. Please explain this in more detail.


A user gets an SQL error in the "UCP Edit Global Settings" page if they don't have the permission to use the HMP feature ....
As long as the extension is enabled and a group permission for it isn't set, users in that same group cannot submit the UCP EGS form ... The permission has to be YES for the page/form to perform as usual .. #Thanks

**Comment by rmcgirr83** [comment]
Where is this page located "UCP Edit Global Settings" as I'm not clear on what page that is.  Please describe exactly what you are doing to create that issue.

**Comment by Kreeman** [comment]
1. Download extension (HMP)
2. Enable extension in ACP
3

> Where is this page located "UCP Edit Global Settings" as I'm not clear on what page that is. Please describe exactly what you are doing to create that issue.

1. Download the extension (HMP)
2. Unzip the extension and upload it to the ext/ directory of the phpbb board
3. Enable the extension in the ACP extension manager ...
4. Return back to board index page
5. Go to User Control Panel UCP, navigate to Board Preferences Tab and to Edit Global Settings page/form/module .. Then SUBMIT ...

Please do just that  (no permissions needed)

**Comment by Kreeman** [comment]
1. Download extension (HMP)
2. Enable extension in ACP
3

> Where is this page located "UCP Edit Global Settings" as I'm not clear on what page that is. Please describe exactly what you are doing to create that issue.

1. Download the extension (HMP)
2. Unzip the extension and upload it to the ext/ directory of the phpbb board
3. Enable the extension in the ACP extension manager ...
4. Return back to board index page
5. Go to User Control Panel UCP, navigate to Board Preferences Tab and to Edit Global Settings page/form/module .. Then SUBMIT ...

Please do just that  (no permissions needed)

**Comment by rmcgirr83** [comment]
Please try this release and report back if you would.

https://github.com/rmcgirr83/hidemyprofile/releases/tag/v1.0.1

**Comment by Kreeman** [comment]
> Please try this release and report back if you would.
> 
> https://github.com/rmcgirr83/hidemyprofile/releases/tag/v1.0.1

Yes .. Right .. Tested superb and appreciated ... Issue closed I suppose ..

**Comment by rmcgirr83** [comment]
👍
