### ISSUE TITLE
Hide on member list

### ISSUE THREAD

**Issue by WimVDK** [rmcgirr83/hidemyprofile#2]
A user i created and have been testing is still showing on the userlist. If it's not being hidden on the user list, then what's the point of this extension? Just wondering, because i couldn't figure out why that specific user was still showing on the member list.

**Comment by rmcgirr83** [comment]
Use the version in my GitHub.

**Comment by WimVDK** [comment]
The one under releases states version 1.0.4. According to phpbb i'm already using 1.0.5? Or am i missing something?

**Comment by rmcgirr83** [comment]
Sorry misunderstood. The user will show on the userlist but when the name is clicked unless the user is an Administrator, a Moderator or a friend, access to the profile will be denied. Why hide the name of the user in the memberlist? The name of the extension is hidemyprofile, not hidemyusername. ;)

**Comment by WimVDK** [comment]
any chance you could make it? While i don't want to underestimate any possible difficulty, i can only imagine it can't be that hard to add that functionality to this extension or slightly modify it into a new one?

**Comment by rmcgirr83** [comment]
So you want to hide the users name when viewing the member list? What about
when viewing a topic or on the index page where user names are shown or
anywhere else on the forum where a users name is shown?

**Comment by WimVDK** [comment]
Basically i have 2 admins. Myself and one i intend to use solely for administrative purposes (backend and/modding), and my current user would be "demoted" to a standard user or be "made to look like one" by changing the default user group. Hiding it on the member list would also "prevent" it from behing a target for dm's?

On the other hand i was told on phpbb forums themselves that an admin actively engaging on the forums is good PR and i sort of have to agree with them on that too. What's your view on this?
